### ISSUE TITLE
Change PSTN implementation to bridgeAPI

### ISSUE THREAD

**Issue by samyak-jain** [AgoraIO/app-builder-backend#3]
**About:**
Tracking issues are used to record the overall progress of implementation. They are also used as hubs connecting to other relevant issues, e.g., bugs or open design questions. A tracking issue is however not meant for large scale discussion, questions, or bug reports about a feature. Instead, open a dedicated issue for the specific matter.

**Describe Feature being implemented.**
Currently PSTN, which leverages turbobridge uses the voiceAPI implementation. This issue tracks the effort to migrate the implementation to the bridgeAPI offered by turbobridge. 

**Steps:**
- [ ] Make a PR
- [ ] Code review by a Maintainer. 
- [ ] Discussion and Implementation on any suggested changes
- [ ] Update Documentation if necessary

**Comment by samyak-jain** [comment]
Closed by 26e2e91eabe3e172e31e62ef20b3367e8ea8243d
